server:
  port: 8202

spring:
  application:
    name: mq-consumer

rocketmq:
  name-server: 10.10.16.41:9876
  consumer:
    topic: TOPICX
    tag: TAGX
    group: CGX
    group2: CGX2
    group3: CGX3
    access-key: CG_RDATA_SUB
    secret-key: 123123123



